## Tensor 基本操作

In [25]:
import torch 
# 使用 
# torch==1.0.1.post2
# torchvision==0.2.2

In [18]:
'''创建一个没有初始化的 5*3 矩阵'''
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -8.5899e+09, -2.1478e-14],
        [ 3.6902e+19,  7.0065e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -8.5899e+09, -1.7457e-14]])


In [19]:
'''创建一个随机初始化矩阵：'''
x = torch.rand(5, 3)
print(x)

tensor([[0.3968, 0.0722, 0.4312],
        [0.8256, 0.7115, 0.7762],
        [0.9180, 0.4276, 0.8534],
        [0.3366, 0.1112, 0.4256],
        [0.6909, 0.2622, 0.8680]])


In [20]:
# all zero ， 數據類型為 long 
x = torch.zeros(5,3 , dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [21]:
# 从数据中构造张量
x = torch.tensor([4.5, 3])
print(x)

tensor([4.5000, 3.0000])


In [22]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [23]:
# 重载 dtype!， size 是相同的，元素是随机生成的
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-2.1420,  1.1306, -1.4203],
        [-0.5420,  1.0480, -0.4291],
        [-1.0728, -1.9343, -1.0481],
        [ 1.0844,  0.3024, -0.3705],
        [-0.9505, -0.1478,  1.0306]])


In [24]:
print(x.shape)

torch.Size([5, 3])


## Tensor 的運算

In [29]:
y = torch.rand(5,3)
print(x + y )

tensor([[-2.0890,  1.5065, -0.6425],
        [-0.4924,  1.5432, -0.1618],
        [-0.4143, -1.5741, -0.9242],
        [ 1.2986,  0.8774,  0.0775],
        [-0.3836,  0.6756,  1.2177]])


In [30]:
result = torch.empty(5,3)
print('Before add:')
print(result)
torch.add(x, y , out= result)
print('\n\nAfter add:')
print(result)

Before add:
tensor([[ 0.0000e+00, -8.5899e+09, -2.1560e-14],
        [-1.5849e+29,  5.6899e-16,  1.4013e-45],
        [ 5.7240e-16,  1.4013e-45,  5.6161e-16],
        [ 1.4013e-45,  6.8502e-32,  1.4013e-45],
        [ 8.8026e-32,  1.4013e-45,  5.7234e-16]])


After add:
tensor([[-2.0890,  1.5065, -0.6425],
        [-0.4924,  1.5432, -0.1618],
        [-0.4143, -1.5741, -0.9242],
        [ 1.2986,  0.8774,  0.0775],
        [-0.3836,  0.6756,  1.2177]])


原地操作

In [31]:
y.add_(x)
print(y)

tensor([[-2.0890,  1.5065, -0.6425],
        [-0.4924,  1.5432, -0.1618],
        [-0.4143, -1.5741, -0.9242],
        [ 1.2986,  0.8774,  0.0775],
        [-0.3836,  0.6756,  1.2177]])


改变形状

In [32]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [33]:
# 只有一个元素
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9139])
0.9139273166656494
