In [1]:
import torch

创建一个张量并设置requires_grad=True用来追踪其计算历史

In [11]:
x = torch.ones(2,2, requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


做运算

In [12]:
y = x + 2 
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


更多操作

In [13]:
z = y * y * 3
out = torch.mean(z)
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


现在开始求导

In [14]:
out.backward()

print(x.grad)

# 其實就是 d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


一个雅可比向量积的例子

In [18]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1052.5164,  201.2552, -335.5588], grad_fn=<MulBackward0>)


在这种情况下，y不再是标量。torch.autograd不能直接计算完整的雅可比矩阵，但是如果我们只想要雅可比向量积，只需将这个向量作为参数传给backward

In [19]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype= torch.float)
y.backward(v)
print(v.shape, y.shape)

torch.Size([3]) torch.Size([3])


In [20]:
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])
